### PR TITLE
DAT257-9 Create Country, Data and DataPoint contracts

### PR DESCRIPTION
**Pull request by filipkauffeldt**
Added Contracts for creating a Country with Data

### CODE REVIEW

**Review by Flaskhals68 — DISMISSED** [review]

**Comment by erbergli** [comment]
Should these objects be mutable or immutable?

**Comment by filipkauffeldt** [comment]
> Should these objects be mutable or immutable?

They should probably be immutable. Will change this.

**Review by erbergli — APPROVED** [review]
LGTM!!!

**Review by Huffla — APPROVED** [review]
Good

**Pull request merged**
